name: Ejercicio 4

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test en matriz de SO
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Mostrar sistema operativo
        run: echo "Sistema operativo: ${{ runner.os }}"

      - name: Ejecutar comando según SO
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            echo "Corriendo en Windows";
          else
            echo "Corriendo en Linux o Mac";
          fi
        shell: bash
